export enum ErrorCode {
  // Authentication & Authorization
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_PERMISSION_DENIED = 'AUTH_PERMISSION_DENIED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  VALIDATION_FIELD_REQUIRED = 'VALIDATION_FIELD_REQUIRED',
  VALIDATION_FORMAT_INVALID = 'VALIDATION_FORMAT_INVALID',
  VALIDATION_VALUE_TOO_LONG = 'VALIDATION_VALUE_TOO_LONG',

  // Resource state
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  RESOURCE_LOCKED = 'RESOURCE_LOCKED',
  RESOURCE_GONE = 'RESOURCE_GONE',

  // Infrastructure
  INFRASTRUCTURE_HTTP_ERROR = 'INFRASTRUCTURE_HTTP_ERROR',
  INFRASTRUCTURE_NETWORK_ERROR = 'INFRASTRUCTURE_NETWORK_ERROR',
  INFRASTRUCTURE_TIMEOUT = 'INFRASTRUCTURE_TIMEOUT',
  INFRASTRUCTURE_SERVICE_UNAVAIL = 'INFRASTRUCTURE_SERVICE_UNAVAIL',
  INFRASTRUCTURE_UNKNOWN = 'INFRASTRUCTURE_UNKNOWN',
}

export interface AppError {
  readonly code: ErrorCode;
  readonly message: string;
  readonly context: Record<string, unknown>;
  readonly retryable: boolean;
  readonly httpStatus: number | null;
  readonly fieldErrors: Record<string, string> | null;
  readonly originalError: unknown;
}

export const HTTP_STATUS_TO_ERROR_CODE: Readonly<Record<number, ErrorCode>> = {
  400: ErrorCode.VALIDATION_ERROR,
  401: ErrorCode.AUTH_TOKEN_INVALID,
  403: ErrorCode.AUTH_PERMISSION_DENIED,
  404: ErrorCode.RESOURCE_NOT_FOUND,
  408: ErrorCode.INFRASTRUCTURE_TIMEOUT,
  409: ErrorCode.RESOURCE_CONFLICT,
  410: ErrorCode.RESOURCE_GONE,
  423: ErrorCode.RESOURCE_LOCKED,
  429: ErrorCode.INFRASTRUCTURE_HTTP_ERROR,
  500: ErrorCode.INFRASTRUCTURE_HTTP_ERROR,
  502: ErrorCode.INFRASTRUCTURE_HTTP_ERROR,
  503: ErrorCode.INFRASTRUCTURE_SERVICE_UNAVAIL,
  504: ErrorCode.INFRASTRUCTURE_TIMEOUT,
};

export const RETRYABLE_HTTP_STATUSES: ReadonlySet<number> = new Set([408, 429, 503, 504]);
